// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaR0pHGep-5_kuLgj4ZDliqNR6NcnEBm8',
    appId: '1:522565209822:web:4a23fc11b56a89e6567c4f',
    messagingSenderId: '522565209822',
    projectId: 'fluttercrm-27c6a',
    authDomain: 'fluttercrm-27c6a.firebaseapp.com',
    storageBucket: 'fluttercrm-27c6a.firebasestorage.app',
    measurementId: 'G-PS111C94GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjJ-WYpZmqUPe4V_Ckkr-BVl1tLjXYiBw',
    appId: '1:522565209822:android:d0a6eecb36714ebe567c4f',
    messagingSenderId: '522565209822',
    projectId: 'fluttercrm-27c6a',
    storageBucket: 'fluttercrm-27c6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9U0hzDkSbed2xQOVzMqOPj4a2JfLyuGg',
    appId: '1:522565209822:ios:16123efdc6ff6875567c4f',
    messagingSenderId: '522565209822',
    projectId: 'fluttercrm-27c6a',
    storageBucket: 'fluttercrm-27c6a.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

}